In [109]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import smtplib
import time
import datetime
import csv

In [110]:
URL = 'https://www.amazon.com/Funny-Data-Systems-Business-Analyst/dp/B07FNW9FGJ/ref=sr_1_3?dchild=1&keywords=data%2Banalyst%2Btshirt&qid=1626655184&sr=8-3&customId=B0752XJYNL&th=1'

headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-GB,en;q=0.9,en-US;q=0.8,fr-FR;q=0.7,fr;q=0.6",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0"
  }

page = requests.get(URL, headers = headers)

Soup1 = BeautifulSoup(page.content, 'html.parser')
print(Soup1.prettify())

<!DOCTYPE html>
<html class="a-no-js" data-19ax5a9jf="dingo" lang="en-us">
 <!-- sp:feature:head-start -->
 <head>
  <script>
   var aPageStart = (new Date()).getTime();
  </script>
  <meta charset="utf-8"/>
  <!-- sp:end-feature:head-start -->
  <!-- sp:feature:csm:head-open-part1 -->
  <script type="text/javascript">
   var ue_t0=ue_t0||+new Date();
  </script>
  <!-- sp:end-feature:csm:head-open-part1 -->
  <!-- sp:feature:cs-optimization -->
  <meta content="on" http-equiv="x-dns-prefetch-control"/>
  <link href="https://images-na.ssl-images-amazon.com" rel="dns-prefetch"/>
  <link href="https://m.media-amazon.com" rel="dns-prefetch"/>
  <link href="https://completion.amazon.com" rel="dns-prefetch"/>
  <!-- sp:end-feature:cs-optimization -->
  <!-- sp:feature:csm:head-open-part2 -->
  <script type="text/javascript">
   window.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;
if (window.ue_ihb === 1) {

var ue_csm = window,
    ue_hob = +new Date();
(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);


    var ue_err_chan = 'jserr-rw';
(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"");b.logLevel=c;b.attribution=f.attribution||b.attribution;a.erl.push({ex:f,info:b})}}function l(a,b,c,e,g){d.ueLogError({m:a,f:b,l:c,c:""+e,err:g,fromOnError:1,args:arguments},g?{attribution:g.attribution,logLevel:g.logLevel}:void 0);return!1}var k="FATAL",m="ERROR",n="WARN",p="DOWNGRADED",a={ec:0,ecf:0,
pec:0,ts:0,erl:[],ter:[],buffer:[],mxe:50,startTimer:function(){a.ts++;setInterval(function(){d.ue&&a.pec<a.ec&&d.uex("at");a.pec=a.ec},1E4)}};l.skipTrace=1;h.skipTrace=1;h.isStub=1;d.ueLogError=h;d.ue_err=a;e.onerror=l})(ue_csm,window);


var ue_id = 'D5JWC3QZZ3YRVR3R63XJ',
    ue_url = '/rd/uedata',
    ue_navtiming = 1,
    ue_mid = 'ATVPDKIKX0DER',
    ue_sid = '133-4787483-6216149',
    ue_sn = 'www.amazon.com',
    ue_furl = 'fls-na.amazon.com',
    ue_surl = 'https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.prod',
    ue_int = 0,
    ue_fcsn = 1,
    ue_urt = 3,
    ue_rpl_ns = 'cel-rpl',
    ue_ddq = 1,
    ue_fpf = '//fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:133-4787483-6216149:D5JWC3QZZ3YRVR3R63XJ$uedata=s:',
    ue_sbuimp = 1,
    ue_ibft = 0,
    ue_sswmts = 0,
    ue_jsmtf = 0,
    ue_fnt = 0,
    ue_lpsi = 6000,
    ue_lob = '1',
    ue_sjslob = 0,
    ue_dsbl_cel = 1,

    ue_swi = 1;
var ue_viz=function(){(function(b,f,d){function g(){return(!(p in d)||0<d[p])&&(!(q in d)||0<d[q])}function h(c){if(b.ue.viz.length<w&&!r){var a=c.type;c=c.originalEvent;/^focus./.test(a)&&c&&(c.toElement||c.fromElement||c.relatedTarget)||(a=g()?f[s]||("blur"==a||"focusout"==a?t:u):t,b.ue.viz.push(a+":"+(+new Date-b.ue.t0)),a==u&&(b.ue.isl&&x("at"),r=1))}}for(var r=0,x=b.uex,a,k,l,s,v=["","webkit","o","ms","moz"],e=0,m=1,u="visible",t="hidden",p="innerWidth",q="innerHeight",w=20,n=0;n<v.length&&!e;n++)if(a=
v[n],k=(a?a+"H":"h")+"idden",e="boolean"==typeof f[k])l=a+"visibilitychange",s=(a?a+"V":"v")+"isibilityState";h({});e&&f.addEventListener(l,h,0);m=g()?1:0;d.addEventListener("resize",function(){var a=g()?1:0;m!==a&&(m=a,h({}))},{passive:!0});b.ue&&e&&(b.ue.pageViz={event:l,propHid:k})})(ue_csm,ue_csm.document,ue_csm.window)};window.ue_viz=ue_viz;

(function(d,h,O){function I(a){return a&&a.replace&&a.replace(/^\s+|\s+$/g,"")}function v(a){return"undefined"===typeof a}function D(a,b){for(var c in b)b[w](c)&&(a[c]=b[c])}function J(a){try{var b=O.cookie.match(RegExp("(^| )"+a+"=([^;]+)"));if(b)return b[2].trim()}catch(c){}}function P(m,b,c){var p=(z||{}).type;if("device"!==c||2!==p&&1!==p)m&&(d.ue_id=a.id=a.rid=m,x&&(x=x.replace(/((.*?:){2})(\w+)/,function(a,b){return b+m})),F&&(e("id",F,m),F=0)),b&&(x&&(x=x.replace(/(.*?:)(\w|-)+/,function(a,
c){return c+b})),d.ue_sid=b),c&&a.tag("page-source:"+c),d.ue_fpf=x}function Q(){var a={};return function(b){b&&(a[b]=1);b=[];for(var c in a)a[w](c)&&b.push(c);return b}}function A(d,b,c,p){p=p||+new G;var f,l;if(b||v(c)){if(d)for(l in f=b?e("t",b)||e("t",b,{}):a.t,f[d]=p,c)c[w](l)&&e(l,b,c[l]);return p}}function e(d,b,c){var e=b&&b!=a.id?a.sc[b]:a;e||(e=a.sc[b]={});"id"===d&&c&&(R=1);return e[d]=c||e[d]}function S(d,b,c,e,f){c="on"+c;var l=b[c];"function"===typeof l?d&&(a.h[d]=l):l=function(){};b[c]=
function(a){f?(e(a),l(a)):(l(a),e(a))};b[c]&&(b[c].isUeh=1)}function T(m,b,c,p){function q(b,c){var d=[b],g=0,f={},l,h;c?(d.push("m=1"),f[c]=1):f=a.sc;for(h in f)if(f[w](h)){var p=e("wb",h),k=e("t",h)||{},n=e("t0",h)||a.t0,q;if(c||2==p){p=p?g++:"";d.push("sc"+p+"="+h);for(q in k)v(k[q])||null===k[q]||d.push(q+p+"="+(k[q]-n));d.push("t"+p+"="+k[m]);if(e("ctb",h)||e("wb",h))l=1}}!y&&l&&d.push("ctb=1");return d.join("&")}function l(b,c,g,e,m){if(b){var f=d.ue_err;d.ue_url&&!e&&!m&&b&&0<b.length&&(e=
new Image,a.iel.push(e),e.src=b,a.count&&a.count("postbackImageSize",b.length));x?(m=h.encodeURIComponent)&&b&&(e=new Image,b=""+d.ue_fpf+m(b)+":"+(+new G-d.ue_t0),a.iel.push(e),e.src=b):a.log&&(a.log(b,"uedata",{n:1}),a.ielf.push(b));f&&!f.ts&&f.startTimer();a.b&&(f=a.b,a.b="",l(f,c,g,1))}}function s(b){var c=z?z.type:B,d=2==c||a.isBFonMshop,c=c&&!d,e=a.bfini;if(!R||a.isBFCache)e&&1<e&&(b+="&bfform=1",c||(a.isBFT=e-1)),d&&(b+="&bfnt=1",a.isBFT=a.isBFT||1),a.ssw&&a.isBFT&&(a.isBFonMshop&&(a.isNRBF=
0),v(a.isNRBF)&&(d=a.ssw(a.oid),d.e||v(d.val)||(a.isNRBF=1<d.val?0:1)),v(a.isNRBF)||(b+="&nrbf="+a.isNRBF)),a.isBFT&&!a.isNRBF&&(b+="&bft="+a.isBFT);return b}if(!a.paused&&(b||v(c))){for(var k in c)c[w](k)&&e(k,b,c[k]);a.isBFonMshop||A("pc",b,c);k="ld"===m&&b&&e("wb",b);var t=e("id",b)||a.id;k||t===a.oid||(F=b,ca(t,(e("t",b)||{}).tc||+e("t0",b),+e("t0",b),K?e("pty",b):B,K?e("spty",b):B));var t=e("id",b)||a.id,u=e("id2",b),g=a.url+"?"+m+"&v="+a.v+"&id="+t,y=e("ctb",b)||e("wb",b),C;y&&(g+="&ctb="+y);
u&&(g+="&id2="+u);1<d.ueinit&&(g+="&ic="+d.ueinit);if(!("ld"!=m&&"ul"!=m||b&&b!=t)){if("ld"==m){try{h[L]&&h[L].isUeh&&(h[L]=null)}catch(J){}if(h.chrome)for(u=0;u<M.length;u++)U(H,M[u]);(u=O.ue_backdetect)&&u.ue_back&&u.ue_back.value++;d._uess&&(C=d._uess());a.isl=1}a._bf&&(g+="&bf="+a._bf());d.ue_navtiming&&f&&(e("ctb",t,"1"),a.isBFonMshop||A("tc",B,B,N));!E||a.isBFonMshop||V||(f&&D(a.t,{na_:f.navigationStart,ul_:f.unloadEventStart,_ul:f.unloadEventEnd,rd_:f.redirectStart,_rd:f.redirectEnd,fe_:f.fetchStart,
lk_:f.domainLookupStart,_lk:f.domainLookupEnd,co_:f.connectStart,_co:f.connectEnd,sc_:f.secureConnectionStart,rq_:f.requestStart,rs_:f.responseStart,_rs:f.responseEnd,dl_:f.domLoading,di_:f.domInteractive,de_:f.domContentLoadedEventStart,_de:f.domContentLoadedEventEnd,_dc:f.domComplete,ld_:f.loadEventStart,_ld:f.loadEventEnd,ntd:("function"!==typeof E.now||v(N)?0:new G(N+E.now())-new G)+a.t0}),z&&D(a.t,{ty:z.type+a.t0,rc:z.redirectCount+a.t0}),V=1);a.isBFonMshop||D(a.t,{hob:d.ue_hob,hoe:d.ue_hoe});
a.ifr&&(g+="&ifr=1")}A(m,b,c,p);var r,n;k||b&&b!==t||da(b);(c=d.ue_mbl)&&c.cnt&&!k&&(g+=c.cnt());k?e("wb",b,2):"ld"==m&&(a.lid=I(t));for(r in a.sc)if(1==e("wb",r))break;if(k){if(a.s)return;g=q(g,null)}else c=q(g,null),c!=g&&(c=s(c),a.b=c),C&&(g+=C),g=q(g,b||a.id);g=s(g);if(a.b||k)for(r in a.sc)2==e("wb",r)&&delete a.sc[r];C=0;a._rt&&(g+="&rt="+a._rt());c=h.csa;if(!k&&c)for(n in r=e("t",b)||{},c=c("PageTiming"),r)r[w](n)&&c("mark",ea[n]||n,r[n]);k||(a.s=0,(n=d.ue_err)&&0<n.ec&&n.pec<n.ec&&(n.pec=n.ec,
g+="&ec="+n.ec+"&ecf="+n.ecf),C=e("ctb",b),"ld"!==m||b||a.markers?a.markers&&a.isl&&!k&&b&&D(a.markers,e("t",b)):(a.markers={},D(a.markers,e("t",b))),e("t",b,{}));a.tag&&a.tag().length&&(g+="&csmtags="+a.tag().join("|"),a.tag=Q());n=a.viz||[];(r=n.length)&&(g+="&viz="+n.splice(0,r).join("|"));v(d.ue_pty)||(g+="&pty="+d.ue_pty+"&spty="+d.ue_spty+"&pti="+d.ue_pti);a.tabid&&(g+="&tid="+a.tabid);a.aftb&&(g+="&aftb=1");!a._ui||b&&b!=t||(g+=a._ui());g+="&lob="+(d.ue_lob||"0");a.a=g;l(g,m,C,k,b&&"string"===
typeof b&&-1!==b.indexOf("csa:"))}}function da(a){var b=h.ue_csm_markers||{},c;for(c in b)b[w](c)&&A(c,a,B,b[c])}function y(a,b,c){c=c||h;if(c[W])c[W](a,b,!1);else if(c[X])c[X]("on"+a,b)}function U(a,b,c){c=c||h;if(c[Y])c[Y](a,b,!1);else if(c[Z])c[Z]("on"+a,b)}function $(){function a(){d.onUl()}function b(a){return function(){c[a]||(c[a]=1,T(a))}}var c={},e,f;d.onLd=b("ld");d.onLdEnd=b("ld");d.onUl=b("ul");e={stop:b("os")};h.chrome?(y(H,a),M.push(a)):e[H]=d.onUl;for(f in e)e[w](f)&&S(0,h,f,e[f]);
d.ue_viz&&ue_viz();y("load",d.onLd);A("ue")}function ca(e,b,c,f,q){var l=d.ue_mbl,s=h.csa,k=s&&s("SPA"),s=s&&s("PageTiming");l&&l.ajax&&l.ajax(b,c);k&&s&&(e={requestId:e,transitionType:"soft"},K&&("string"===typeof f&&(e.pageType=f,d.ue_pty=f),"string"===typeof q&&(e.subPageType=q,d.ue_spty=q)),k("newPage",e),s("mark","transitionStart",b));a.tag("ajax-transition")}d.ueinit=(d.ueinit||0)+1;var a=d.ue=d.ue||{};a.t0=h.aPageStart||d.ue_t0;a.id=d.ue_id;a.url=d.ue_url;a.rid=d.ue_id;a.a="";a.b="";a.h={};
a.s=1;a.t={};a.sc={};a.iel=[];a.ielf=[];a.viz=[];a.v="0.315547.0";a.paused=!1;var w="hasOwnProperty",H="beforeunload",L="on"+H,W="addEventListener",Y="removeEventListener",X="attachEvent",Z="detachEvent",ea={cf:"criticalFeature",af:"aboveTheFold",fn:"functional",fp:"firstPaint",fcp:"firstContentfulPaint",bb:"bodyBegin",be:"bodyEnd",ld:"loaded"},G=h.Date,E=h.performance||h.webkitPerformance,f=(E||{}).timing,z=(E||{}).navigation,N=(f||{}).navigationStart,x=d.ue_fpf,R=0,V=0,M=[],F=0,K=d.ue_a2ptyl,B;
a.oid=I(a.id);a.lid=I(a.id);a._t0=a.t0;a.tag=Q();a.ifr=h.top!==h.self||h.frameElement?1:0;a.markers=null;a.attach=y;a.detach=U;if("000-0000000-8675309"===d.ue_sid){var aa=J("cdn-rid"),ba=J("session-id");aa&&ba&&P(aa,ba,"cdn")}d.uei=$;d.ueh=S;d.ues=e;d.uet=A;d.uex=T;a.reset=P;a.pause=function(d){a.paused=d};$()})(ue_csm,ue_csm.window,ue_csm.document);


ue.stub(ue,"event");ue.stub(ue,"onSushiUnload");ue.stub(ue,"onSushiFlush");

ue.stub(ue,"log");ue.stub(ue,"onunload");ue.stub(ue,"onflush");
(function(b){function f(){var a={requestId:b.ue_id||"rid",server:b.ue_sn||"sn",obfuscatedMarketplaceId:b.ue_mid||"mid"};b.ue_sjslob&&(a.lob=b.ue_lob||"0");return a}var a=b.ue;a.cv={};a.cv.scopes={};a.cv.buffer=[];a.count=function(b,d,c){var e=a.cv;a.d();c&&c.scope&&(e=a.cv.scopes[c.scope]=a.cv.scopes[c.scope]||{});if(void 0===d)return e[b];e[b]=d;a.cv.buffer.push({c:b,v:d})};a.count("baselineCounter2",1);a&&a.event&&(a.event(f(),"csm","csm.CSMBaselineEvent.4"),a.count("nexusBaselineCounter",1,{bf:1}))})(ue_csm);


(function(g,h,l){if("function"===typeof h.addEventListener&&"function"===typeof l.querySelectorAll){var e,r=["mouseenter","mouseleave"],t="click dblclick mousedown mouseover mouseout touchstart keydown keypress MSPointerDown pointerdown focusin".split(" ").concat(r),n=!1,p=[];var u=function(a){for(var b=[];a;)b.push(a),a=a.parentNode;return b};var q=function(a,b){var d=-1,c;for(c=0;c<b.length;c++)if(b[c]===a){d=c;break}return d};var v=function(a,b){a=q(a,b);0<=a&&b.splice(a,1)};var x=function(a){a=
u(a);for(var b,d,c=0;c<a.length;c++)if(d=a[c],(b=d.nodeName)&&b!==l.nodeName){b=b.toLowerCase();if(d.id)return b+"#"+d.id+(f?">"+f:"");(d=d.getAttribute("class"))&&(b=b+"."+d.split(" ").join("."));var f=b+(f?">"+f:"")}return f};var y=function(a){return a.replace(/[^\w.:\-]/g,function(a){return"#"===a?"::":">"===a?":-":"_"})};var w=function(a,b){if(g.ue&&g.ue.count&&g.ueLogError){a=x(a);var d=y(a);var c="degraded"===b?"A UX degrading element has entered the viewport: "+a:"A "+b+" was not handled on element: "+
a;g.ueLogError({m:c,fromOnError:1},{logLevel:"ERROR",attribution:a,message:c});b=["TNR","TNR:"+b,"TNR:"+d,"TNR:"+b+":"+d];for(e=0;e<b.length;e++)g.ue.count(b[e],(g.ue.count(b[e])||0)+1)}};var z=function(a){a=a.getBoundingClientRect();return a.top<a.bottom&&a.left<a.right&&0<=a.bottom&&a.top<=h.innerHeight&&0<=a.right&&a.left<=h.innerWidth};var m=function(){n||(n=!0,setTimeout(function(){[].forEach.call(l.querySelectorAll("[data-ux-degraded]"),function(a){z(a)?0>q(a,p)&&(p.push(a),w(a,"degraded")):
v(a,p)});n=!1},250))};h.addEventListener("scroll",m);h.addEventListener("resize",m);m=function(a){var b=!1,d=0>q(a,r);l.addEventListener(a,function(c){if(!b){b=!0;var f=[],e=d?u(c.target):[c.target],g,h;for(g=0;g<e.length;g++){var k=e[g];k.getAttribute&&("mouseover"===a&&k===c.target&&((h=k.getAttribute("data-ux-jq-mouseenter"))||""===h)&&f.push(k),((h=k.getAttribute("data-ux-"+a))||""===h)&&f.push(k))}f.length?(c.ack=c.acknowledge=function(a){a=a||c.currentTarget;v(a,f)},setTimeout(function(){var c;
for(c=0;c<f.length;c++)w(f[c],a);b=!1},250)):b=!1}},!0)};for(e=0;e<t.length;e++)m(t[e])}})(ue_csm,window,document);


var ue_hoe = +new Date();
}
window.ueinit = window.ue_ihb;
  </script>
  <!-- 61csm6etlvwhw9wt9xanh35ldfzkfq5mf307xnkv8ifvlqbve -->
  <script>
   window.ue && ue.count && ue.count('CSMLibrarySize', 12307)
  </script>
  <!-- sp:end-feature:csm:head-open-part2 -->
  <!-- sp:feature:aui-assets -->
  <link href="https://m.media-amazon.com/images/I/11EIQ5IGqaL._RC|01ZTHTZObnL.css,41mbvf3ie8L.css,31ztmKxuc5L.css,11+NvJNwWJL.css,01xH+fhFIJL.css,01qVdqPr5xL.css,413Vvv3GONL.css,11TIuySqr6L.css,01Rw4F+QU6L.css,11ZP-tjHxjL.css,01LmAy9LJTL.css,01IdKcBuAdL.css,014QJx7nWqL.css,01bwGDJt6oL.css,016EnqvinxL.css,21KKU-zL4lL.css,01qSaWIViCL.css,51JeiWKN2tL.css,01Hp8zG27eL.css,01XPHJk60-L.css,116IPKI32xL.css,01GAxF7K5tL.css,01UUHfXZHOL.css,21g-w9XAw+L.css,01ZE1gfHIAL.css,21POIeN-EdL.css,11wGcpAJUpL.css,31mhKSefPKL.css,01CFUgsA-YL.css,315haCJ0QHL.css,11PDZ29p-PL.css,111AzStFuOL.css,115hGi2N00L.css,11sUwulETuL.css,11K2vxAewLL.css,01HdzRh5tAL.css,21jtJjVIBbL.css,214H13jznAL.css,01akUMqBphL.css,21CScBPc+5L.css,11F-m79SjbL.css,11utsyuU0aL.css,11m5rWsq0zL.css,01890+Vwk8L.css,01+fnLEdpwL.css,01qiwJ7qDfL.css,21TAMzcrOKL.css,016mfgi+D2L.css,01bBfQy8rmL.css,21NlrZ0zbSL.css,21xK8DIvuEL.css,013-xYw+SRL.css_.css?AUIClients/AmazonUI#us.not-trident" rel="stylesheet">
   <link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/61xJcNKKLXL.js?AUIClients/AmazonUIjQuery" rel="preload">
    <link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/11zuylp74DL._RC|11Y+5x+kkTL.js,51LPrROZ2JL.js,11EeeaacI2L.js,11GgN1+C7hL.js,01+z+uIeJ-L.js,01VRMV3FBdL.js,21NadQlXUWL.js,01vRf9id2EL.js,11a7qqY8xXL.js,11rRjDLdAVL.js,51C4kaFbiAL.js,11FhdH2HZwL.js,11wb9K3sw0L.js,11BrgrMAHUL.js,11GYEyswV2L.js,210X-JWUe-L.js,01Svfxfy8OL.js,51hrOUe5lOL.js,01ikBbTAneL.js,31KAF--uG1L.js,01qXJuwGmxL.js,01WlsjNmqIL.js,11F929pmpYL.js,31vxRYDelFL.js,01rpauTep4L.js,31wjiT+nvTL.js,011FfPwYqHL.js,21vGxgxnRsL.js,01Oec+wqgPL.js,21kN0q4IA-L.js,11vb6P5C5AL.js,01iUHbNmzgL.js_.js?AUIClients/AmazonUI#372963-T1" rel="preload">
     <link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/51FKj+gURkL.js?AUIClients/CardJsRuntimeBuzzCopyBuild" rel="preload"/>
     <script>
      (function(b,a,c,d){if((b=b.AmazonUIPageJS||b.P)&&b.when&&b.register){c=[];for(a=a.currentScript;a;a=a.parentElement)a.id&&c.push(a.id);return b.log("A copy of P has already been loaded on this page.","FATAL",c.join(" "))}})(window,document,Date);(function(a,b,c,d){"use strict";a._pSetI=function(){return null}})(window,document,Date);(function(b,a,J,C){"use strict";b._pd=function(){var c,v;return function(D,e,g,h,d,E,w,F,G){function x(b){try{return b()}catch(K){return!1}}function p(c){return b.matchMedia?b.matchMedia(c):{matches:!1}}function k(){if(l){var y=c.mobile||c.tablet?q.matches&&m.matches:m.matches;if(z!==y){var a={w:b.innerWidth||d.clientWidth,h:b.innerHeight||d.clientHeight};if(17<Math.abs(r.w-a.w)||50<Math.abs(r.h-a.h))r=a,(z=y)?h(d,"a-ws"):d.className=w(d,"a-ws")}}}function H(b){(l=b===C?!l:!!b)&&k()}function I(){return l}
if(!v){v=!0;var t=function(){var b=["O","ms","Moz","Webkit"],c=a.createElement("div");return{testGradients:function(){return!0},test:function(a){var d=a.charAt(0).toUpperCase()+a.substr(1);a=(b.join(d+" ")+d+" "+a).split(" ");for(d=a.length;d--;)if(""===c.style[a[d]])return!0;return!1},testTransform3d:function(){return!0}}}();g=d.className;var A=/(^| )a-mobile( |$)/.test(g),B=/(^| )a-tablet( |$)/.test(g);c={audio:function(){return!!a.createElement("audio").canPlayType},video:function(){return!!a.createElement("video").canPlayType},
canvas:function(){return!!a.createElement("canvas").getContext},svg:function(){return!!a.createElementNS&&!!a.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},dragDrop:function(){return"draggable"in a.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!b.history||!b.history.pushState)},webworker:function(){return!!b.Worker},
autofocus:function(){return"autofocus"in a.createElement("input")},inputPlaceholder:function(){return"placeholder"in a.createElement("input")},textareaPlaceholder:function(){return"placeholder"in a.createElement("textarea")},localStorage:function(){return"localStorage"in b&&null!==b.localStorage},orientation:function(){return"orientation"in b},touch:function(){return"ontouchend"in a},gradients:function(){return t.testGradients()},hires:function(){var a=b.devicePixelRatio&&1.5<=b.devicePixelRatio||
b.matchMedia&&b.matchMedia("(min-resolution:144dpi)").matches;F("hiRes"+(A?"Mobile":B?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return t.testTransform3d()},touchScrolling:function(){return e(/Windowshop|android|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|SOFTWARE=([5-9]|[1-9][0-9]+)(.[0-9]{1,2})+.*DEVICE=iPhone|Chrome|Silk|Firefox|Trident.+?; Touch/i)},ios:function(){return e(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!e(/trident|Edge/i)},android:function(){return e(/android.([1-9]|[L-Z])/i)&&
!e(/trident|Edge/i)},mobile:function(){return A},tablet:function(){return B},rtl:function(){return"rtl"===d.dir}};for(var f in c)c.hasOwnProperty(f)&&(c[f]=x(c[f]));for(var u="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),n=0;n<u.length;n++)c[u[n]]=x(function(){return t.test(u[n])});var l=!0,r={w:0,h:0},q=p("(orientation:landscape)"),m=c.mobile||c.tablet?p("(min-width:451px)"):p("(min-width:1250px)");q.addListener&&q.addListener(k);m.addListener&&
m.addListener(k);var z;k();d.className=w(d,"a-no-js");h(d,"a-js");!e(/OS [1-8](_[0-9]*)+ like Mac OS X/i)||b.navigator.standalone||e(/safari/i)||h(d,"a-ember");g=[];for(f in c)c.hasOwnProperty(f)&&c[f]&&g.push("a-"+f.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));h(d,g.join(" "));d.setAttribute("data-aui-build-date",G);D.register("p-detect",function(){return{capabilities:c,localStorage:c.localStorage&&E,toggleResponsiveGrid:H,responsiveGridEnabled:I}});return c||{}}}}()})(window,document,
Date);(function(g,h,E,F){function N(a){l&&l.tag&&l.tag(p(":","aui",a))}function q(a,b){l&&l.count&&l.count("aui:"+a,0===b?0:b||(l.count("aui:"+a)||0)+1)}function O(a){try{return a.test(navigator.userAgent)}catch(b){return!1}}function x(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d)}function p(a,b,d,e){b=b&&d?b+a+d:b||d;return e?p(a,b,e):b}function y(a,b,d){try{Object.defineProperty(a,b,{value:d,writable:!1})}catch(e){a[b]=d}return d}function P(a,b){a.className=

In [111]:
title = Soup1.find(id="productTitle").get_text().strip()
print(title)

price_whole = Soup1.find(class_='a-price-whole').get_text(strip=True)
price_fraction = Soup1.find(class_='a-price-fraction').get_text(strip=True)
price = f'{price_whole}{price_fraction}'
print(price)

Got Data Funny Business Data Analyst T-Shirt
23.97

In [112]:
today = datetime.date.today()
print(today)

2025-07-16

In [113]:
header = ['Title', 'Price','Date']
data = [title, price, today]

with open("AmazonWebScraperDataset.csv", "w", newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerow(data)

In [114]:
df = pd.read_csv("AmazonWebScraperDataset.csv")

df

# df.drop_duplicates(inplace=True)

# df

                                          Title  Price        Date
0  Got Data Funny Business Data Analyst T-Shirt  23.97  2025-07-16

In [115]:
# appending data

with open("AmazonWebScraperDataset.csv", "a", newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(data)

In [ ]:
def send_mail():
    server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
    server.ehlo()
    server.login('vinitprg@gmail.com', 'XXXXXXXXXXXXXXX')
    
    subject = 'Price fell down!'
    body = f'Check the Amazon link: {URL}'
    msg = f'Subject: {subject}\n\n{body}'
    
    server.sendmail('vinitprg@gmail.com', msg)

In [ ]:
def check_price():
    URL = 'https://www.amazon.com/Funny-Data-Systems-Business-Analyst/dp/B07FNW9FGJ/ref=sr_1_3?dchild=1&keywords=data%2Banalyst%2Btshirt&qid=1626655184&sr=8-3&customId=B0752XJYNL&th=1'

    headers = {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-GB,en;q=0.9,en-US;q=0.8,fr-FR;q=0.7,fr;q=0.6",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0"
    }

    page = requests.get(URL, headers = headers)

    Soup1 = BeautifulSoup(page.content, 'html.parser')
    
    title = Soup1.find(id="productTitle").get_text().strip()

    price_whole = Soup1.find(class_='a-price-whole').get_text(strip=True)
    price_fraction = Soup1.find(class_='a-price-fraction').get_text(strip=True)
    price = f'{price_whole}{price_fraction}'
    
    today = datetime.date.today()

    header = ['Title', 'Price','Date']
    data = [title, price, today]

    with open("AmazonWebScraperDataset.csv", "a+", newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(data)
        
    if price < "20":
        send_mail()

In [117]:
while True:
    check_price()
    time.sleep(5)

KeyboardInterrupt:

In [118]:
df = pd.read_csv("AmazonWebScraperDataset.csv")

df

                                          Title  Price        Date
0  Got Data Funny Business Data Analyst T-Shirt  23.97  2025-07-16
1  Got Data Funny Business Data Analyst T-Shirt  23.97  2025-07-16
2  Got Data Funny Business Data Analyst T-Shirt  23.97  2025-07-16
3  Got Data Funny Business Data Analyst T-Shirt  23.97  2025-07-16
4  Got Data Funny Business Data Analyst T-Shirt  23.97  2025-07-16
5  Got Data Funny Business Data Analyst T-Shirt  23.97  2025-07-16